# This is a sample build configuration for C++.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: rabits/qt:5.12-desktop

pipelines:
  default:
    - step:
        script:
          - sudo apt-get update -y
          - sudo apt-get install cmake -y
          - cmake .
          - make